### ISSUE TITLE
two files created in the collection one is zero

### ISSUE THREAD

**Issue by shalaby** [vsivsi/meteor-file-collection#106]
Hello, Thanks @vsivsi , this library is awesome, my problem  is for every file I upload two files created in the collection one of them is zero : 
<img width="752" alt="robomongo 0 9 0-rc7 robomongo today at 10 57 06 pm" src="https://cloud.githubusercontent.com/assets/149119/14944004/7076852e-0ff0-11e6-936e-6e1fdc976a10.png">

**Comment by vsivsi** [comment]
I can't help unless you provide a minimal reproduction case, preferably in the form of a github repo containing a meteor app that clearly demonstrates the problem you are having. 

This is almost certainly a bug in your code someplace, and I'm happy to help, but I need to see you code for that to happen.

**Comment by shalaby** [comment]
Thanks @vsivsi for your quick response, I appreciate this 👍 
https://github.com/shalaby/fs-collection-test

**Comment by vsivsi** [comment]
Hi, I just got around to trying this out, but I can get your app to start correctly. Since you didn't add any instructions, I just tried:

```
git clone https://github.com/shalaby/fs-collection-test.git
cd fs-git-collection
meteor
```

This is what I get in return:
![screen shot 2016-05-02 at 2 10 42 pm](https://cloud.githubusercontent.com/assets/428642/14968064/c521c686-106f-11e6-8a6e-348000a34176.png)

I'm sorry, but I don't have the time to spend effort just to get your app to start correctly.  As I said, I'm happy to try to help, but you need to provide a truly minimal reproduction case: the minimum amount of code that illustrates the problem. Thanks.

**Comment by shalaby** [comment]
@vsivsi I am really grateful for you and I am truly sorry for wasting your time, the project I am working on is using Angular2, anyway I am closing this issue because I solved it, it was my mistake, but it made me know that you are a very supportive, and cooperative and that's good to know 👍
