### ISSUE TITLE
Is jquery required

### ISSUE THREAD

**Issue by DavidSichau** [vsivsi/meteor-file-collection#153]
I want to avoid to deliver jquery to my clients. However your package depends on jquery, however I do not find any reference in the code to jquery. Is it actually really required and where?

Can you point me to the code which requires jquery, such that I can generate a pull request without jquery dependecy.

**Comment by vsivsi** [comment]
Hi, It didn't used to be, but at some point resumable.js apparently added a dependency on it in this pull request. 
https://github.com/23/resumable.js/pull/343

Then they apparently reversed that on this issue. This thread would be funny if it wasn't so sad...
https://github.com/23/resumable.js/issues/344

Anyway, looks like it isn't really a dependency so I'll remove it in the next release (later this week).

As a side note, I'd really like to make resumable.js a fully optional dependency of this project so that better (and better managed) upload solutions such as [tus](https://github.com/tus/tus-js-client) or [flowjs](https://github.com/flowjs/flow.js) could be (also optionally) supported. Someday...

**Comment by DavidSichau** [comment]
@vsivsi Thanks for the fix, when is it planed to be released?

**Comment by vsivsi** [comment]
I'll do it before this weekend.

**Comment by vsivsi** [comment]
Just released and published to atmosphere in version 1.3.8
