### ISSUE TITLE
Any samples without upload/download functionality?

### ISSUE THREAD

**Issue by LevanArabuli** [vsivsi/meteor-file-collection#173]
Is there a sample which just stores and retrieves data from GridFS, no upload/download functionality?

**Comment by vsivsi** [comment]
So just for server-side use only?
There aren’t any sample apps for that because that case is potentially so much simpler...

You are basically just restricting yourself to setting up the fileCollection object and using the last four server-side API methods starting here:
https://github.com/vsivsi/meteor-file-collection#fcfindonestreamselector-options-callback

Each of those methods has example usage code snippets in the documentation linked above.

**Comment by LevanArabuli** [comment]
Sounds great, thanks!

**Comment by vsivsi** [comment]
I should mention that you can, and of course will, also use the normal Collection/MongoDB methods: find, findOne, update, remove, and you should look to the docs for how the semantics of those methods map to fileCollection.
