### ISSUE TITLE
an example of token based authentification

### ISSUE THREAD

**Issue by Billybobbonnet** [vsivsi/meteor-file-collection#46]
Hello,

First, @vsivsi , this is a great package. I had no trouble to make it work based on the example. The thing that bugs me is that for now I use the cookie based authentication. I would like to switch on http header with token solution. I am quite new to javascript/meteor and I wonder how it should be done.

I tried to do it using jQuery $.ajaxSetup to add it into the header but it didn't work. I have also tried to add this to the template rendered function
```javascript
Files.resumable.headers  = {
      'X-Auth-Token': Accounts._storedLoginToken()
    }
```
The truth is that I have no clue on what is the right way to do this. Do you have an example?

**Comment by vsivsi** [comment]
Hi, just a quick response... I don't have much time today to dig into this.

 I'm not sure that including the token in the HTTP header will work.  I feel like I've tried this method with resumable.js in the past and there was some issue, but now I don't recall exactly what it was.  You can try it, and watch the HTTP requests in your browser and see what happens. I feel like maybe the custom headers you set only apply to the POST requests, but not the GET requests that resumable.js generates to test if a given chunk has already been uploaded before sending it. Obviously, if those GETs fail with 403s, then that will cause a problem. I'm working off almost 1 year old memories here. Anyway, the cookie method works because the auth token is then certain to be seemlessly included in both GET and POST requests. 

I share your general distaste for cookies, however keep in mind that under the hood, cookies are also just transmitted within the HTTP header. The cookie you set can be restricted to a specific URL path related to your file-collection, etc.  

I can look into this more next week if you'd like and figure out what the issue was with the X-Auth-Token header and resumable.js  It may be that they've fixed it in the past year or so, or maybe I was just doing it wrong, but I do clearly recall that using a cookie was the path of least resistance at the time.

**Comment by vsivsi** [comment]
@Billybobbonnet 

Hi, I just looked into this more closely and using resumable.js for uploading with the `X-Auth-Token` HTTP header works fine now.  You were almost there with your code above, but it is buried a bit more deeply...

```js
Files.resumable.opts.headers['X-Auth-Token']  = Accounts._storedLoginToken();
```
Be sure to put this code within an `Tracker.autorun` function that depends on `Meteor.userId()` so that the resumable.js header state reflects the currently authenticated user at all times.

BTW, if you want to disable the resumable.js feature that performs the "test GETs" that return 404 errors, you may that too:

```js
Files.resumable.opts.testChunks = false;
```

In this case, chunks may be uploaded multiple times if the client loses sync with the server, because there is no other mechanism to verify which chunks have already been received. I strongly recommend leaving `testChunks` enabled, but I understand that the 404 errors it produces may be undesirable in some applications.

Hope that helps.

**Comment by vsivsi** [comment]
FYI, I've added branch to the file-collection sample app that uses the X-Auth-Token HTTP header instead of the cookie.  Note that with this code the app is "upload only" because any attempt to GET a file (while authenticated as a user) will fail with a 403 because no token is provided to authenticate the request.

See:
https://github.com/vsivsi/meteor-file-sample-app/tree/use_header_x_auth_token

**Comment by Billybobbonnet** [comment]
Thank you very much @vsivsi. This is very helpful. You made my day :-)

I will look into this tomorrow and try a few ideas for the GET requests (I am thinking to a Javascript request helper which add the userId as url param). I assume it would lead me into a small PR on the package to change its server-side file serving feature. 

This is something I needed to try eventually because I also wanted to add a new url parameter in order to use the gridFS range parameter. While I am quite new at this, I expect it to make streaming video files more effective (e.g. by directly loading the relevant video range when seeking, if it is not cached yet.) My google foo didn't work well on this matter, so since I don't have any info on this, I will just try it. I mention it just in case you already experienced a similar use case.

My way forward would be to add an "on the fly" encoding feature during upload, but I'm not there yet. (see https://github.com/trenskow/stream-transcoder.js)

Thanks again for your help, I'm closing the issue :+1:

**Comment by vsivsi** [comment]
Hi, @Billybobbonnet 

Quite a bit of work has already gone into file-collection to support video streaming/seeking.  Specifically, it fully supports the HTTP range request mechanism. So no need to hack that into URL queries. See: https://github.com/vsivsi/meteor-file-collection/pull/27

Also, there is support for URL parameters to control the server-side cache headers:
https://github.com/vsivsi/meteor-file-collection#http-request-behaviors

Early versions of file-collection allowed the Meteor authentication token to be passed as a URL query, but that feature was removed from the prototype because it is way too easy for a user to mistakenly share that token with others by e.g. passing the link to some file in an email or public posting of some kind. If such a link gets out, it would allow an adversary to take over the account associated with that token anytime before it expires, so we decided to eliminate that method of authentication in favor of the cookie approach, which doesn't have that issue (a user would need to work hard to "accidentally" share the contents of a cookie!)

Re:  "...a Javascript request helper which add the userId as url param"
This approach will be highly insecure. userIds are not secret (and may be easily guessable), so any scheme that depends on simply providing the userId in a URL query to identify the user to authenticate  an HTTP request is doomed to be easily circumvented. Perhaps your application doesn't require much security, I don't know, but I would strongly advise against this approach.

**Comment by Billybobbonnet** [comment]
Concerning the userId as url param, it was misguided and you're right to underline the security risk. Not to mention the extra work requested. I moved towards a XmlHttpRequest alternative and still wondering why I came up with that url parameter idea :laughing: . 

I am working on something to handle the file url in a form like 
{{ file id="theIdOfTheFile" download=false cache="172800" }}

Here is a first, untested&unfinished, draft of the helper so you get an idea:

```javascript
// Helper dedicated to serve files.
//---------------------------------
//DESCRIPTION:
// It executes an asynchronous XMLHttpRequest by using the following features
// "id" : file unique Id
// "progress" : percentage of the file delivered
// "is" : state of the download {"requested", "denied", "granted","downloading","downloaded", "error", "not_found"}
// "range" : range of the file which has been requested. Video/audio only.
// "download": is it for file download (bool)
// "cache": cache control max age
// "filename": target name of the downloaded file
//-----------------------------------


// event handlers
function onProgress(e) {
  this.is = "downloading";
  this.progress = = (e.position / e.totalSize)*100;this.is = "downloading";
}

function onError(e) {
  this.is = ("error");
}

function onLoad(e) {
  this.is = ("downloading");
}
//instantiate the XMLHttpRequest
this.xhr = new XMLHttpRequest();

this.xhr.open('GET', files.path + this.id, true);
//add security token
this.xhr.setRequestHeader('X-Auth-Token', Accounts._storedLoginToken());
this.is = "requested"

// link event handlers
this.xhr.onload = onLoad;
this.xhr.onerror = onError;
this.xhr.onprogress = onProgress;
this.xhr.onreadystatechange = function (aEvt) {
  if (this.xhr.readyState == 4) {
    if(this.xhr.status == 200)
    this.is = ("downloaded")
    dump(this.xhr.responseText);
    else
    this.is = "error";
    if(this.xhr.status == 403)
    {
      this.is = "denied"
    }
    if(this.xhr.status == 404)
    {
      this.is = "not_found"
    }
    
  }
};
this.xhr.send(null);
```
I need to carefully read the https://github.com/vsivsi/meteor-file-collection/pull/27 and get a better understanding of the HTTP range request mechanism and how it has been implemented in file-collection.

**Comment by vsivsi** [comment]
Is your client a Meteor client? If so, you may be able to use the [HTTP.call()](http://docs.meteor.com/#/full/http_call) interface to save yourself a bunch of work. XHR is yucky.

**Comment by Billybobbonnet** [comment]
yes it is. Thanks for the info, I'll look into it :)

**Comment by Billybobbonnet** [comment]
I am puzzled by this. I expected to be able to somehow directly feed an img or video src from a HTTP.get request. It seems that it can't be done that way, and based on [similar examples](http://www.philten.com/us-xmlhttprequest-image/) with XmlHTTPRequest, I understood that the result.content of the HTTP.get must be encoded in base64 to be displayed. 

I gave it a try by replacing the {{link}} helper with the following code (the encode64 function is elsewhere):

```javascript
	link : function(){
		HTTP.get (Files.baseURL + "/" + this.md5,
		{
			headers:{
				"X-Auth-Token": Accounts._storedLoginToken()
			}
		},
		function (error, result) {
			if (error){
				console.log ("an error " + result.statusCode + " occured");
			}
			else
			{
				retval ="";
				for (var i=0; i<=result.content.length-1; i++)
				retval += String.fromCharCode(result.content.charCodeAt(i) & 0xff);
				return "data:"+this.contentType+";base64," + encode64(retval)
			}
		})
		return "/images/tile.png"
	},
```
I manage to get the image (seen in network console with 200 code) but not to display it. I guess it is because I call an async function in an helper, which then returns "undefined".

But before I go further, I wanted your opinion : I wonder if this will get me anywhere. Here I deal with images, but what if this is video? This kind of approach suppose to:
1- issue the GET request with token
2- download the file
3- convert it
4- pass it as dataUrl

I assume that it will put a significant load on the client, force me to do in 4 steps what could have been done in one, and probably create problems with video streaming. Unless I overlook obvious options, it does not seems to be a viable approach to me. Do you agree? If so, I guess I'll go back to the cookie approach :cry:

**Comment by vsivsi** [comment]
Hi, like I said in my original response, using a cookie is the path of least resistance!

This SO answer seems to be highly cited for images: http://stackoverflow.com/questions/4285042/can-jquery-ajax-load-image/12714338#12714338

As for streaming videos, I agree that this approach probably won't be satisfactory. 

To do that, you might consider another approach:
1) Call a custom Meteor method requesting a certain video by id (or whatever)
2) Method implementation checks userId again video file metadata
3) If allowed the method creates a new random id, and records it in the video metadata (with a time stamp). This id is returned by a successful method call. 
4) the server defines a http path for accessing videos using an alternative id, and allow rules that permit reading data using such URLs without authentication
5) now the client may read the video data directly without authentication using the alternate id, which is acting as an alternate token

Wrinkles to the above: the video alternate id metadata needs to be able hold multiple alternate ids simultaneously, in case multiple different readers want the same video simultaneously.  There also needs to be a way to delete old alternate video ids, based on the time stamp. Depending on the security requirements, you may also need to keep track of which ids are generated for which users so that if a userId is banned or deleted, any temporary ids generated can be immediately deleted, etc. etc. 

I'm confident this approach would work, it's how a lot of CDNs seem to operate.  Question for you is if it's worth all of this trouble to avoid using a cookie.

**Comment by Billybobbonnet** [comment]
Your approach makes sense. It is certainly more troublesome than the cookie way but it has one advantage to me: I wanted to include in served video metadata a track of the userId and time of request. Not that it isn't possible with cookies, could you say.

My intuition is that security could be lessened since a video could then be shared between non authorized users with a simple url during the time of availability of the temporary id. Since tokens are stateless, I couldn't disable the url when the user close his browser without adding a user session tracking package/feature.

Either way, I thank you again for your precious insight. I will sleep on that.

**Comment by vsivsi** [comment]
I'm unclear on what precisely this means:
>  I wanted to include in served video metadata a track of the userId and time of request. 

1.  Does this mean that you want the gridFS file metedata for the video to be updated?
2.  Or does it mean that you want metadata within the video stream itself to be modified to record the userId and time?

Either way, I think you could do it with the cookie or with some other authentication scheme. Obviously if option 2 is what you want, then you will need to heavily customize the HTTP request handler to modify the video stream as it is sent, a nontrivial operation!  Option 1 would probably also require a custom request handler, although perhaps that little bit of logic could be added to an allow rule for the file-collection, or maybe even the lookup function for the HTTP path definition.

**Comment by Billybobbonnet** [comment]
I meant the first option, achieved by changing the allow rule. It seems to be feasible without too much difficulty. Option 2 would be a pain, but if I had to guess how to make it, I would watermark some parts of the video stream using the FFMPEG transcoding package (see https://github.com/trenskow/stream-transcoder.js). But it would be kind of overkill :smile: 

Regarding our earlier topic, all things well considered, I will probably choose the cookie way for now. 

Since I also planned to contribute to @perak 's Meteor-kitchen, I am curious to hear his opinion on it.

Of course, if I deal with the token header approach later, I will keep you in the loop.

Thanks!
