### ISSUE TITLE
Mongo: namespace too long error

### ISSUE THREAD

**Issue by poojabansal** [vsivsi/meteor-file-collection#55]
I have a fileCollection by the name of 'covers'.
On running jasmine client integration tests, I am seeing the following error log:

```MongoError: namespace name generated from index name "jasmine-client-integration.covers.files.$metadata._Resumable.resumableIdentifier_1_metadata._Resumable.resumableChunkNumber_1_length_1" is too long (127 byte max)```

I noticed this error only on updating meteor from v1.0.3.2 to v1.1.0.2.

**Comment by vsivsi** [comment]
Seems like a Jasmine issue to me...  file-collection isn't generating that huge name.

file-collection is responsible for the naming of `.metadata._Resumable.resumableIdentifier` and `.metadata._Resumable.resumableChunkNumber`, but it's unclear to me why jasmine (or whatever) is combining those two separate attributes into one name like that.

I any case, I'm not currently a jasmine user, so I'm afraid I can't be of much help to you in debugging this issue.

**Comment by vsivsi** [comment]
Just to add a possible hint... Those two fields form a MongoDB index in the database:
https://github.com/vsivsi/meteor-file-collection/blob/master/gridFS_server.coffee#L62

So that explains why they are being combined (it's not random...)

The index being generated in mongoDB by that code is:
```json
	{
		"v" : 1,
		"key" : {
			"metadata._Resumable.resumableIdentifier" : 1,
			"metadata._Resumable.resumableChunkNumber" : 1,
			"length" : 1
		},
		"name" : "metadata._Resumable.resumableIdentifier_1_metadata._Resumable.resumableChunkNumber_1_length_1",
		"ns" : "meteor.images.files",
		"safe" : true
	},
```

**Comment by vsivsi** [comment]
More info:

It appears to be running into this limit in mongodb: http://docs.mongodb.org/manual/reference/limits/#Index-Name-Length

The default index name being generated is 94 characters long.  Jasmine (or whatever) is adding another 42 characters to that (= 136).

I can probably provide a name for that index so that the 94 character long default isn't used, which would probably clear up this issue for you, but that would be a pain to deploy because there are 100s of servers out there running with the present index name, and I'd need to write code to ensure that they are all migrated correctly. So I'm not very inclined to do that...

The actual bug here is with whatever code is blindly adding 32 characters to an existing 94 character name and not bothering to check if that exceeds the namespace length limit (127).

`'jasmine-client-itegration'` appears to be a default name within meteor jasmine:
https://github.com/Sanjo/meteor-jasmine/blob/b17a85bb1894886e3904866f7525aa5d49098bff/src/client/integration/ClientIntegrationTestFramework.js#L21

I have no idea where the code is that combines that name with a collection and index name, but it's probably within meteor-jasmine, so I'd go asking over there... 

Okay, I hope that helps.  That's about I can do.

**Comment by poojabansal** [comment]
Thanks Vaughn for the insights into this issue.

**Comment by Sanjo** [comment]
`jasmine-client-integration` is the name of the MongoDB database that is used. So the issue is that if the database name is a bit longer, the limit is exceeded.

I suggest that you explicitly specify a shorter index name like stated in the documentation of MongoDB.

> Fully qualified index names, which includes the namespace and the dot separators (i.e. <database name>.<collection name>.$<index name>), cannot be longer than 128 characters.

> By default, <index name> is the concatenation of the field names and index type. You can explicitly specify the <index name> to the ensureIndex() method to ensure that the fully qualified index name does not exceed the limit.

http://docs.mongodb.org/v2.6/reference/method/db.collection.ensureIndex/#db.collection.ensureIndex

It's the name option.

**Comment by vsivsi** [comment]
@Sanjo  Thanks.  As I said above, although the default index name being generated isn't ideal, it has already been deployed to a lot of running servers.  So changing it at this point would involve a lot more than just specifying a new shorter name in the code.  MongoDB does not allow the name of an existing index to be changed, it must be dropped and re-added.  And dropping a nonexistent index will generate an error message on start-up if the Meteor provided call `_dropIndex` is unconditionally used. 

So basically, changing this the right way would involve writing a bunch of code at the raw MongoDB driver level to inspect what indexes are present on the collection, and then dropping and rebuilding the old index if present. That's not ideal from a maintenance perspective because the raw mongo driver can change underneath Meteor, and they don't guarantee forward compatibility (the 1.4 -> 2.0 transition is coming, eventually)  And since indexes are referred to by their name in various MongoDB calls, this would technically be a breaking change to my package (sort of akin to renaming a method in its API) and so would necessitate a semver major revision bump...

All this because some code in another package outside of my control is creating a database name by concatenating some strings together from sources it doesn't control without checking that the resulting name is too long to be valid?  No thank you. 

Anyway, as I said above, I'm not inclined to "fix" this issue by creating a breaking change in my package, when the bug lies elsewhere.  I will make a note to change this index name whenever I release the next major revision of this package with other breaking changes, but that will likely be awhile (months or more).

It will be 20x easier to fix this problem with a check at the point those strings are being combined to make the new DB name, and that is arguably the correct thing to do in any case.

**Comment by poojabansal** [comment]
Thanks Vaughn, I do second your opinion on it.

**Comment by Sanjo** [comment]
If you don't shorten your index name, this means that your package does not work with databases which name is longer than 20 characters.

> It will be 20x easier to fix this problem with a check at the point those strings are being combined to make the new DB name, and that is arguably the correct thing to do in any case.

This happens in MongoDB. I could shorten the name `jasmine-client-integration` to be shorter than 20 characters.

**Comment by vsivsi** [comment]
I will add an option to allow the developer to specify the index name. You will need to manually delete the old index with the long default name after you change your code.. The default index name will remain the same (until 2.0) so no running servers will be impacted by this change. I'll post here again when the change has been published to Atmosphere with more detail, probably later tonight.

**Comment by vsivsi** [comment]
This change has been made in file-collection v1.1.1, just published.

To solve your issue, add the `resumableIndexName` option to any/all file collections
```js
myData = new FileCollection('album', {
   resumable: true,     // Enable the resumable.js compatible chunked file upload interface
   resumableIndexName: 'someName',  // chose a short name of the index  
   // ....
);
```
This will cause the resumable internal index to use the name "someName" instead of the default, the next time the index is rebuilt.

To trigger a rebuild of the index, you must manually drop it and then restart your meteor app.

To drop the old index (the one with the default MongoDB created name):

```bash
# In the mongo shell:
 db.covers.files.dropIndex("metadata._Resumable.resumableIdentifier_1_metadata._Resumable.resumableChunkNumber_1_length_1")
```

Your database must be running when you run the `dropIndex` above.  If you use an external mongodb instance, I assume you know how to do that.  If you are still running in developer mode, you can access the mongo shell by typing `meteor mongo` in your app subdirectory while the app is running.

Please let me know if this solves your issue. If you have and problems let me know.

**Comment by poojabansal** [comment]
The fix worked perfectly. Thanks @vsivsi!
