### ISSUE TITLE
Question about POST with file in multipart/form-data

### ISSUE THREAD

**Issue by katopz** [vsivsi/meteor-file-collection#65]
Hi guys, 

Refer to
```curl
# POST with file in multipart/form-data
curl -X POST 'http://127.0.0.1:3000/gridfs/fs/38a14c8fef2d6cef53c70792' \
     -F 'file=@"lolcat.gif";type=image/gif' \
     -H 'X-Auth-Token: 3pl5vbN_ZbKDJ1ko5JteO3ZSTrnQIl5g6fd8XW0U4NQ'
```
Here's my question
* I use https://github.com/vsivsi/meteor-file-sample-app so `/gridfs/fs/` is my baseURL am I right?
* If is not, Is there any example for this or I need to implement myself?

Refer to
```
The file with _id = 38a14c8fef2d6cef53c70792 must exist
```
* When I want to upload new file, where can I get file id? from my understand I should upload file and server will give me file id after add file to collection isn't it?

Refer to
```
# The auth token should match a logged-in userId
```
* I got token but I can't see no where to put `userId` parameter via curl?

Thanks

**Comment by vsivsi** [comment]
> I use https://github.com/vsivsi/meteor-file-sample-app so /gridfs/fs/ is my baseURL am I right?
> If is not, Is there any example for this or I need to implement myself?
The sample app does not define a POST upload route because it uses resumable.js.  You can define one here: https://github.com/vsivsi/meteor-file-sample-app/blob/master/sample.coffee#L13

Something like this should do:

```coffee
   { method: 'post', path: '/id/:_id', lookup: (params, query) -> return { _id: params._id }}
```

> When I want to upload new file, where can I get file id? from my understand I should upload file and server will give me file id after add file to collection isn't it?

If the uploader is Meteor client code, you can create the file and get the `_id` value by simply calling `_id = fc.insert()` in your client code. You'll also need allow/deny rules for that. 

If you would like to upload some other way. Then you'll need to cause that insert to happen some other way:
* define a Meteor method and call it using the DDP npm package. 
* define an HTTP API route using one of the Atmosphere packages that allow you to map HTTP requests to Meteor Methods or other calls
* build the insert into the `lookup` function you define for the POST upload route.  Be sure to think hard about the security implications of this. 

> I got token but I can't see no where to put userId parameter via curl?

The token is a complete temporary identifier for an authenticated user. The userId is looked up on the server using the token you provide (assuming the token is valid).

**Comment by katopz** [comment]
@vsivsi Cool! Thanks for your answer. :santa: 

Cheers!

**Comment by vsivsi** [comment]
One wrinkle to the last part of my answer... The lookup function doesn't get called with the `req` object, so it can't do the Meteor userID lookup. 

However the 'write' allow/deny functions gets the user ID and can insert the file. But that's kind of a kludge. 

The best way would probably be to write a 'handler' function for the POST upload interface that handles the logic, and then allows the default POST handler to handle writing the file data. You'd need to be familiar with writing express.js style route handlers to do this though.

**Comment by katopz** [comment]
I think I'm over do in this case actually I try to upload file from native android/ios which success already with https://github.com/tomitrescak/meteor-uploads but still having [some issue](https://github.com/tomitrescak/meteor-tomi-upload-server/issues/15) so while wait, 
I try to explore for more possibility and I think I've to learn a bit more to get it done ;)

Cheers
