### ISSUE TITLE
No MIME multipart boundary found for dicer

### ISSUE THREAD

**Issue by nicolamr** [vsivsi/meteor-file-collection#66]
This bug is kind of hard to define, since it doesn't happen all the time.

Right now I have two instances of the same meteor app, one of which generates this error

   No MIME multipart boundary found for dicer

when I try to upload a file. The very same instance worked fine yesterday. And trying to upload the same file on the other instance works.

**Comment by nicolamr** [comment]
Update: this is somehow firefox-specific, as it works in chrome.

**Comment by vsivsi** [comment]
When the error happens, does it continue to happen consistently in that instance, or is it truly intermittent?  Can you make the error happen using the unmodified sample app?  

https://github.com/vsivsi/meteor-file-sample-app

I have tested extensively against that app, and have never encountered this (nor has anyone else reported such a problem in the history of the project). 

It sounds like for whatever reason, under some circumstances your client resumable.js POST upload of file chunks are being interrupted (socket closed, etc) which is causing the error because the full payload of a chunk isn't arriving intact, leading to the dicer error. However, I would expect the upload to continue, or to be resumable, by resending that chunk. It's kind of the whole point of resumable.js!

Anyway, I can't help debug an intermittent error in your app without your code and a lot more information, steps to reproduce, etc.  Which is why I ask if you can make this happen with the sample app. If you can, then I'd be happy to take a look and try to reproduce it.  Otherwise, I'm not sure how I can help.

**Comment by nicolamr** [comment]
Thank you for your answer. Meanwhile I was able to have it run with an other connection. It looks like the cause really was just a bad connection. I'm going to close this issue, automatically delete the failed file and print an error message. If the issue comes again and becomes unacceptable I'll test the sample app.

**Comment by vsivsi** [comment]
Okay, good luck.  Intermittent network problems are the worst.
