### ISSUE TITLE
How to detect upload complete?

### ISSUE THREAD

**Issue by dpatte** [vsivsi/meteor-file-collection#68]
In my code I am using
Myfiles.resumable.upload();

But how would I detect upload complete?

**Comment by dpatte** [comment]
Got it:.

  Myfiles.resumable.on('fileSuccess', function(file)  {
    toastr["success"](file.fileName+" Uploaded");
  });

**Comment by vsivsi** [comment]
That works, I use it in the unit tests here: https://github.com/vsivsi/meteor-file-collection/blob/master/test/file_collection_tests.coffee#L731

The other way is to subscribe to the collection on the client, and then add an observer waiting for the length of the newly inserted file to change from zero to the final size.  This method is probably more useful if you are uploading large files, since there may be a small lag between the client uploading the last chunk and the file becoming available (the mongo server calculates the md5 sum, requiring the entire file to be read before it becomes available).

**Comment by keyscores** [comment]
@vsivsi I'm wondering if it's worthwhile for file-collection itself to set a file { metadata: { complete: true } }  when the md5 sum is created. 

For my app I've implemented a small server-side method to do this, since .update() is nota available on the client. This makes using observeChanges much easier on both server and client. It's probably not a breaking change.

**Comment by vsivsi** [comment]
The amount of code to implement that observe yourself seems small (10-15 lines) and, especially on the server, unnecessary observes are undesirable. I'd rather leave it for the developer, since it is so simple to do yourself.
