### ISSUE TITLE
Will this package work with hosting on *.meteor.com servers?

### ISSUE THREAD

**Issue by PranayShah** [vsivsi/meteor-file-collection#69]
Another file upload package displays this warning. 
>WARNING If you plan to deploy your solution to free *.meteor.com servers, this solution is not for you, since you have no write access outside of standard Meteor directories. Please use CollectionFS instead.

I am guessing this should not be a problem unless one wants to save to the filesystem, while this package stores to Mongo, Am I correct in thinking so?

**Comment by vsivsi** [comment]
Should be correct, yes.  GridFS is MongoDB only, and this package even writes temporary data (uploaded chunks) to gridFS. I'm pretty sure CollectionFS writes them to the file system,  I avoided that because it requires everything be copied an extra time, whereas within gridFS just references need to change.

**Comment by PranayShah** [comment]
Thanks.
